### 🔹 1. Introdução ao Pandas

O **Pandas** é uma biblioteca Python que facilita a manipulação de **dados tabulares**.

#### Principais vantagens:

* Conexão com diversas fontes (CSV, Excel, Parquet)
* Estruturas de dados poderosas
* Fácil análise e transformação de dados

### 🔹 2. Tipos de Dados no Pandas

O Pandas usa o **NumPy** como base.

#### Tipos comuns:

* `int`, `float`, `bool`
* `object` → strings, listas, dicionários
* `datetime64` → datas
* `category` → dados categóricos (economiza memória)

### 🔹 3. Series (Coluna)

Uma **Series** é uma estrutura unidimensional (como uma coluna).

#### Componentes:

* Um conjunto de dados unidimensional, que podem ser de qualquer tipo
* Um índice (index) que é usado para acessar cada dado da Series. O índice geralmente é um número inteiro ou uma string (Object)

#### Criando Series:

* Objetos do Python:
    * Listas e Tuplas: Index numérico será gerado de forma automática
    * Dicionários: O index da Series vão ser as Chaves do dicionário
* Arquivos CSV e Excel com apenas uma coluna também podem ser lidos para criar Series.

In [136]:
import pandas as pd

# Lista
serie1 = pd.Series([1, 2, 3])
serie1

0    1
1    2
2    3
dtype: int64

In [137]:
# Dicionário
serie2 = pd.Series({"A": 1, "B": 2, "C": 3})
serie2

A    1
B    2
C    3
dtype: int64

### 🔹 4. DataFrames

Um **DataFrame** é uma tabela (linhas e colunas).

* Cada coluna é uma Series
* Possui índice para as linhas

### 🔹 5. Leitura de Arquivos

#### CSV

In [138]:
# Leitura de um arquivo CSV
# função: pd.read_csv()
df_csv = pd.read_csv('data/4-introduction_to_pandas/arquivo_teste.csv', sep=";")
df_csv

   id     nome  idade     cidade  faturamento
0   1      Ana     23      Natal         2500
1   2    Bruno     35     Recife         4000
2   3   Carlos     29  Fortaleza         3200
3   4    Diana     41      Natal         5000
4   5  Eduardo     22     Recife         1800

#### Excel

In [139]:
# Leitura de um arquivo EXCEK
# função: read_excel()
# o parâmetro sheet_name é utilizado para especificar a planilha/aba a ser lida
df_xlsx = pd.read_excel('data/4-introduction_to_pandas/arquivo_teste.xlsx', sheet_name="Plan1")
df_xlsx

   id     nome  idade     cidade  faturamento
0   1      Ana     23      Natal         2500
1   2    Bruno     35     Recife         4000
2   3   Carlos     29  Fortaleza         3200
3   4    Diana     41      Natal         5000
4   5  Eduardo     22     Recife         1800

### 🔹 6. Atributos e Métodos Básicos

In [140]:
df = pd.read_csv('data/4-introduction_to_pandas/funcionarios.csv', sep=";")

In [141]:
df.shape        # (linhas, colunas)

(20, 7)

In [142]:
df.columns      # nomes das colunas

Index(['id', 'nome', 'idade', 'data', 'salario', 'ativo', 'id_departamento'], dtype='object')

In [143]:
df.index        # índice

RangeIndex(start=0, stop=20, step=1)

In [144]:
df.head()       # primeiras linhas

,id,nome,idade,data,salario,ativo,id_departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Bianca Vasconcelos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4

In [145]:
df.tail()       # últimas linhas

,id,nome,idade,data,salario,ativo,id_departamento
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

In [146]:
df.info()       # resumo do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               20 non-null     int64
 1   nome             20 non-null     object
 2   idade            20 non-null     int64
 3   data             20 non-null     object
 4   salario          20 non-null     float64
 5   ativo            20 non-null     bool
 6   id_departamento  20 non-null     int64
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 1.1+ KB

### 🔹 7. Acessando Dados

#### Colunas

In [147]:
# Acessa uma coluna (retorna uma Series)
df["nome"]

0      Sra. Isabela Vasconcelos
1               Heitor Teixeira
2            Bianca Vasconcelos
3                 Alice Machado
4             Antônio Fernandes
5         Henry Gabriel da Mata
6     Sra. Maria Luiza Oliveira
7                  Isis Marques
8             Sr. Vitor da Rosa
9                  Théo Cardoso
10            Marcelo Rodrigues
11           Maria Clara Santos
12                   Sofia Rios
13            Benicio das Neves
14                Levi Silveira
15       Maria Fernanda Rezende
16           Thomas Casa Grande
17          Davi Miguel Ribeiro
18       Dr. Mathias Montenegro
19             Samuel Gonçalves
Name: nome, dtype: object

In [148]:
# Acessa múltiplas colunas (retorna um DataFrame)
df[["nome", "salario"]]

                         nome  salario
0    Sra. Isabela Vasconcelos  4435.13
1             Heitor Teixeira  7834.97
2          Bianca Vasconcelos  3094.55
3               Alice Machado  6287.20
4           Antônio Fernandes  7138.43
5       Henry Gabriel da Mata  4941.62
6   Sra. Maria Luiza Oliveira  7111.25
7                Isis Marques  8438.66
8           Sr. Vitor da Rosa  2363.85
9                Théo Cardoso  8029.65
10          Marcelo Rodrigues  8109.35
11         Maria Clara Santos  2601.68
12                 Sofia Rios  4990.01
13          Benicio das Neves  2541.54
14              Levi Silveira  9261.98
15     Maria Fernanda Rezende  7436.21
16         Thomas Casa Grande  8205.90
17        Davi Miguel Ribeiro  2625.01
18     Dr. Mathias Montenegro  9566.83
19           Samuel Gonçalves  3884.99

#### Linhas

In [149]:
# Acessa uma linha pelo índice (label)
# Aqui pega a linha com índice 3 (quarta linha do DF)
df.loc[3]

id                             4
nome               Alice Machado
idade                         40
data                  2023-10-10
salario                   6287.2
ativo                       True
id_departamento                2
Name: 3, dtype: object

In [150]:
# Acessa uma linha pela posição (começa em 0)
# Aqui pega a primeira linha
df.iloc[0]

id                                        1
nome               Sra. Isabela Vasconcelos
idade                                    44
data                             2022-02-11
salario                             4435.13
ativo                                  True
id_departamento                           4
Name: 0, dtype: object

In [151]:
# Intervalo com loc (INCLUSIVO no final)
# Vai pegar as linhas de índice 1, 2 e 3
df.loc[1:3]

   id                nome  idade        data  salario  ativo  id_departamento
1   2     Heitor Teixeira     40  2022-01-17  7834.97  False                2
2   3  Bianca Vasconcelos     44  2022-10-28  3094.55  False                2
3   4       Alice Machado     40  2023-10-10  6287.20   True                2

In [152]:
# Intervalo com iloc (EXCLUSIVO no final)
# Vai pegar posições 1, 2 e 3
df.iloc[1:4]

   id                nome  idade        data  salario  ativo  id_departamento
1   2     Heitor Teixeira     40  2022-01-17  7834.97  False                2
2   3  Bianca Vasconcelos     44  2022-10-28  3094.55  False                2
3   4       Alice Machado     40  2023-10-10  6287.20   True                2

#### Valores específicos

In [153]:
# Acessa um valor específico (linha 3, coluna "nome")
df.at[3, "nome"]

'Alice Machado'

In [154]:
# Acessa por posição (linha 0, coluna 1 → "nome")
df.iat[0, 1]

'Sra. Isabela Vasconcelos'

In [155]:
# Altera um valor específico
df.at[2, "nome"] = "Josicleyton Santos"
df

,id,nome,idade,data,salario,ativo,id_departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Josicleyton Santos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

### 🔹 8. Filtragem de Dados

In [156]:
# Cria uma série booleana (True para salários maiores que 3000)
filtro = df["salario"] > 4000

# Aplica o filtro no DataFrame
df_filtrado = df[filtro]
df_filtrado

,id,nome,idade,data,salario,ativo,id_departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4

#### Operadores:

In [157]:
df_filtrado = df[
    (df["salario"] > 3000) & (df["id_departamento"] == 4)
]
df_filtrado

,id,nome,idade,data,salario,ativo,id_departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4

### 🔹 9. Criando e removendo colunas

In [158]:
# Criar uma nova coluna com base em cálculos
df['salario_anual'] = df['salario'] * 12
df

,id,nome,idade,data,salario,ativo,id_departamento,salario_anual
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4,53221.56
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2,94019.64
2,3,Josicleyton Santos,44,2022-10-28,3094.55,False,2,37134.60
3,4,Alice Machado,40,2023-10-10,6287.20,True,2,75446.40
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4,85661.16
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4,59299.44
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5,85335.00
7,8,Isis Marques,24,2023-02-05,8438.66,True,1,101263.92
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1,28366.20
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2,96355.80
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1,97312.20
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4,31220.16
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1,59880.12
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5,30498.48
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5,111143.76
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3,89234.52
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2,98470.80
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5,31500.12
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4,114801.96
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3,46619.88

In [159]:
# Remover uma coluna
df = df.drop('salario_anual', axis=1)
df

,id,nome,idade,data,salario,ativo,id_departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Josicleyton Santos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3

### 🔹 10. Métodos de Series

#### Estatísticos

In [160]:
# Estatísticos
print(df["salario"].mean())      # média dos salários
print(df["salario"].median())    # mediana
print(df["salario"].mode())      # valor(es) mais frequente(s)
print(df["salario"].min())       # menor salário
print(df["salario"].max())       # maior salário
print(df["salario"].std())       # desvio padrão (variação dos salários)
df["salario"].describe()  # resumo completo (count, mean, std, min, quartis, max)

5944.940499999999
6699.225
0     2363.85
1     2541.54
2     2601.68
3     2625.01
4     3094.55
5     3884.99
6     4435.13
7     4941.62
8     4990.01
9     6287.20
10    7111.25
11    7138.43
12    7436.21
13    7834.97
14    8029.65
15    8109.35
16    8205.90
17    8438.66
18    9261.98
19    9566.83
Name: salario, dtype: float64
2363.85
9566.83
2474.638643924603

count      20.000000
mean     5944.940500
std      2474.638644
min      2363.850000
25%      3687.380000
50%      6699.225000
75%      8049.575000
max      9566.830000
Name: salario, dtype: float64

In [161]:
# Aritméticos
print(df["salario"].add(10))   # soma 10 a cada salário
print(df["salario"].sub(5))    # subtrai 5
print(df["salario"].mul(2))    # multiplica por 2
print(df["salario"].div(2))    # divide por 2

0     4445.13
1     7844.97
2     3104.55
3     6297.20
4     7148.43
5     4951.62
6     7121.25
7     8448.66
8     2373.85
9     8039.65
10    8119.35
11    2611.68
12    5000.01
13    2551.54
14    9271.98
15    7446.21
16    8215.90
17    2635.01
18    9576.83
19    3894.99
Name: salario, dtype: float64
0     4430.13
1     7829.97
2     3089.55
3     6282.20
4     7133.43
5     4936.62
6     7106.25
7     8433.66
8     2358.85
9     8024.65
10    8104.35
11    2596.68
12    4985.01
13    2536.54
14    9256.98
15    7431.21
16    8200.90
17    2620.01
18    9561.83
19    3879.99
Name: salario, dtype: float64
0      8870.26
1     15669.94
2      6189.10
3     12574.40
4     14276.86
5      9883.24
6     14222.50
7     16877.32
8      4727.70
9     16059.30
10    16218.70
11     5203.36
12     9980.02
13     5083.08
14    18523.96
15    14872.42
16    16411.80
17     5250.02
18    19133.66
19     7769.98
Name: salario, dtype: float64
0     2217.565
1     3917.485
2     1547.275
3     3143.600
4     3569.215
5     2470.810
6     3555.625
7     4219.330
8     1181.925
9     4014.825
10    4054.675
11    1300.840
12    2495.005
13    1270.770
14    4630.990
15    3718.105
16    4102.950
17    1312.505
18    4783.415
19    1942.495
Name: salario, dtype: float64

### 🔹 11. Valores `null`

In [162]:
df_null = pd.read_csv('data/4-introduction_to_pandas/funcionarios_dadosnulos.csv', sep=";", na_values=["", " ", "NULL"])
df_null

,id,nome,idade,data_registro,salario,ativo,id_departamento
0,1,NaN,35.0,45293.0,5469.47,True,3.0
1,2,Nicolas Cardoso,45.0,44706.0,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60.0,44931.0,5599.99,True,4.0
3,4,Luiz Fernando Fernandes,NaN,45208.0,6708.07,False,NaN
4,5,Gael Henrique Costela,51.0,44507.0,9497.52,NaN,NaN
5,6,Stephany Pimenta,32.0,45494.0,7123.00,True,NaN
6,7,Bruna Vargas,25.0,44649.0,5036.81,NaN,NaN
7,8,NaN,60.0,45354.0,8219.79,True,5.0
8,9,NaN,47.0,44816.0,4790.53,NaN,4.0
9,10,NaN,NaN,44738.0,8914.27,NaN,4.0
10,11,NaN,NaN,44961.0,4475.88,NaN,NaN
11,12,Manuela Guerra,NaN,44651.0,9883.09,False,NaN
12,13,Dr. Apollo Moraes,NaN,44942.0,5392.79,True,NaN
13,14,Antônio Gonçalves,44.0,NaN,5511.17,True,NaN
14,15,Luara Lima,48.0,NaN,5426.62,True,3.0
15,16,NaN,26.0,NaN,6519.70,False,NaN
16,17,NaN,41.0,45484.0,7815.03,False,5.0
17,18,Isabela Campos,28.0,44733.0,7824.41,False,4.0
18,19,Danilo Rocha,32.0,45511.0,7196.97,False,4.0
19,20,Sara Fonseca,50.0,45174.0,5884.55,True,2.0

In [163]:
df_null.dropna()  # remove linhas com valores nulos

,id,nome,idade,data_registro,salario,ativo,id_departamento
1,2,Nicolas Cardoso,45.0,44706.0,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60.0,44931.0,5599.99,True,4.0
17,18,Isabela Campos,28.0,44733.0,7824.41,False,4.0
18,19,Danilo Rocha,32.0,45511.0,7196.97,False,4.0
19,20,Sara Fonseca,50.0,45174.0,5884.55,True,2.0

In [164]:
df_null.dropna(subset=["id_departamento"])  # remove linhas onde "id_departamento" é nulo

,id,nome,idade,data_registro,salario,ativo,id_departamento
0,1,NaN,35.0,45293.0,5469.47,True,3.0
1,2,Nicolas Cardoso,45.0,44706.0,3824.20,True,4.0
2,3,Lucas Gabriel Sampaio,60.0,44931.0,5599.99,True,4.0
7,8,NaN,60.0,45354.0,8219.79,True,5.0
8,9,NaN,47.0,44816.0,4790.53,NaN,4.0
9,10,NaN,NaN,44738.0,8914.27,NaN,4.0
14,15,Luara Lima,48.0,NaN,5426.62,True,3.0
16,17,NaN,41.0,45484.0,7815.03,False,5.0
17,18,Isabela Campos,28.0,44733.0,7824.41,False,4.0
18,19,Danilo Rocha,32.0,45511.0,7196.97,False,4.0
19,20,Sara Fonseca,50.0,45174.0,5884.55,True,2.0

### 🔹 12. Contando ocorrências, ordenando e combinando dados

In [165]:
df['ativo'].value_counts()  # conta quantas vezes cada valor aparece na coluna "ativo"

ativo
True     11
False     9
Name: count, dtype: int64

In [166]:
df.sort_values("salario", ascending=False)  # ordena por salário (do maior para o menor)

,id,nome,idade,data,salario,ativo,id_departamento
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3
2,3,Josicleyton Santos,44,2022-10-28,3094.55,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1

In [167]:
df_departamentos = pd.read_csv('data/4-introduction_to_pandas/departamentos.csv', sep=";")
df_departamentos

   id_departamento nome_departamento
0                1            Vendas
1                2                TI
2                3                RH
3                4        Financeiro
4                5         Marketing

In [168]:
# Combinando datas frames
df_final = pd.merge(df, df_departamentos)
df_final

,id,nome,idade,data,salario,ativo,id_departamento,nome_departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4,Financeiro
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2,TI
2,3,Josicleyton Santos,44,2022-10-28,3094.55,False,2,TI
3,4,Alice Machado,40,2023-10-10,6287.20,True,2,TI
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4,Financeiro
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4,Financeiro
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5,Marketing
7,8,Isis Marques,24,2023-02-05,8438.66,True,1,Vendas
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1,Vendas
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2,TI
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1,Vendas
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4,Financeiro
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1,Vendas
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5,Marketing
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5,Marketing
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3,RH
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2,TI
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5,Marketing
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4,Financeiro
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3,RH

In [169]:
df_novosfuncionarios = pd.read_csv('data/4-introduction_to_pandas/novosfuncionarios.csv', sep=";")
df_novosfuncionarios

,id,nome,idade,data,salario,ativo,id_departamento
0,1,Maria Clara Cunha,27,2023-03-05,6747.76,True,4
1,2,Luiz Gustavo Barros,18,2022-11-11,5990.81,False,3
2,3,Maria Helena das Neves,19,2024-04-01,7588.55,False,5
3,4,Ravy Camargo,36,2022-01-25,4341.11,False,4
4,5,Cecilia Casa Grande,46,2022-10-30,5716.84,True,4
5,6,Carolina Souza,62,2022-05-02,3305.85,False,4
6,7,Mathias Souza,28,2024-05-02,9782.90,True,4
7,8,Yago Gomes,28,2023-10-17,9615.18,True,1
8,9,Natália Moraes,20,2022-10-03,2798.04,True,5
9,10,João Miguel Caldeira,53,2024-03-12,8941.77,True,1
10,11,Thales Monteiro,55,2022-05-20,7587.85,True,2
11,12,Miguel Pacheco,61,2022-12-22,7690.91,False,2
12,13,Léo da Conceição,40,2023-01-20,7552.60,True,3
13,14,Aurora Carvalho,53,2022-03-27,2954.14,True,1
14,15,Mathias Rocha,44,2024-01-18,9316.01,True,5
15,16,Maria Liz Sampaio,34,2023-12-01,8334.63,False,2
16,17,Arthur Gabriel Cassiano,42,2024-03-23,4275.55,False,4
17,18,Joana Sousa,54,2023-05-20,5755.79,True,5
18,19,Srta. Ana Lívia Silva,21,2023-11-19,7636.43,False,5
19,20,Gustavo Castro,64,2022-02-04,3641.82,True,2

In [170]:
# Concatenando data frames (empilhando um embaixo do outro)
df_completo = pd.concat([df, df_novosfuncionarios], ignore_index=True)
df_completo

,id,nome,idade,data,salario,ativo,id_departamento
0,1,Sra. Isabela Vasconcelos,44,2022-02-11,4435.13,True,4
1,2,Heitor Teixeira,40,2022-01-17,7834.97,False,2
2,3,Josicleyton Santos,44,2022-10-28,3094.55,False,2
3,4,Alice Machado,40,2023-10-10,6287.20,True,2
4,5,Antônio Fernandes,54,2023-08-09,7138.43,True,4
5,6,Henry Gabriel da Mata,42,2024-01-26,4941.62,False,4
6,7,Sra. Maria Luiza Oliveira,58,2024-08-24,7111.25,True,5
7,8,Isis Marques,24,2023-02-05,8438.66,True,1
8,9,Sr. Vitor da Rosa,61,2024-03-25,2363.85,False,1
9,10,Théo Cardoso,54,2022-09-05,8029.65,True,2
10,11,Marcelo Rodrigues,57,2024-02-06,8109.35,True,1
11,12,Maria Clara Santos,39,2023-10-21,2601.68,True,4
12,13,Sofia Rios,45,2023-05-19,4990.01,False,1
13,14,Benicio das Neves,22,2022-04-15,2541.54,True,5
14,15,Levi Silveira,42,2024-02-10,9261.98,True,5
15,16,Maria Fernanda Rezende,29,2023-11-18,7436.21,False,3
16,17,Thomas Casa Grande,33,2024-03-29,8205.90,False,2
17,18,Davi Miguel Ribeiro,48,2022-07-10,2625.01,False,5
18,19,Dr. Mathias Montenegro,20,2023-08-17,9566.83,False,4
19,20,Samuel Gonçalves,21,2023-10-03,3884.99,True,3
20,1,Maria Clara Cunha,27,2023-03-05,6747.76,True,4
21,2,Luiz Gustavo Barros,18,2022-11-11,5990.81,False,3
22,3,Maria Helena das Neves,19,2024-04-01,7588.55,False,5
23,4,Ravy Camargo,36,2022-01-25,4341.11,False,4
24,5,Cecilia Casa Grande,46,2022-10-30,5716.84,True,4
25,6,Carolina Souza,62,2022-05-02,3305.85,False,4
26,7,Mathias Souza,28,2024-05-02,9782.90,True,4
27,8,Yago Gomes,28,2023-10-17,9615.18,True,1
28,9,Natália Moraes,20,2022-10-03,2798.04,True,5
29,10,João Miguel Caldeira,53,2024-03-12,8941.77,True,1
30,11,Thales Monteiro,55,2022-05-20,7587.85,True,2
31,12,Miguel Pacheco,61,2022-12-22,7690.91,False,2
32,13,Léo da Conceição,40,2023-01-20,7552.60,True,3
33,14,Aurora Carvalho,53,2022-03-27,2954.14,True,1
34,15,Mathias Rocha,44,2024-01-18,9316.01,True,5
35,16,Maria Liz Sampaio,34,2023-12-01,8334.63,False,2
36,17,Arthur Gabriel Cassiano,42,2024-03-23,4275.55,False,4
37,18,Joana Sousa,54,2023-05-20,5755.79,True,5
38,19,Srta. Ana Lívia Silva,21,2023-11-19,7636.43,False,5
39,20,Gustavo Castro,64,2022-02-04,3641.82,True,2

In [171]:
# Exportando o DataFrame para CSV e Excel
df_completo.to_csv('data/4-introduction_to_pandas/funcionarios_completos.csv', index=False, sep=";")
df_completo.to_excel('data/4-introduction_to_pandas/funcionarios_completos.xlsx', index=False)

### 🔹 13. GroupBy

Agrupa dados por valores únicos.

* `groupby()`: define os grupos
* Selecionar coluna: define o que será analisado
* Agregação: resume os dados de cada grupo

In [172]:
# Agrupa o DataFrame pelos valores únicos da coluna "cidade"
df.groupby("id_departamento")

In [173]:
df.groupby("id_departamento")["salario"].mean()  # média salarial por departamento

id_departamento
1    5975.4675
2    6690.4540
3    5660.6000
4    5736.7380
5    5384.9450
Name: salario, dtype: float64

---

### 🔹 14. Merge / Join

Semelhante ao **JOIN do SQL**.

* `on="coluna"`: quando a coluna tem mesmo nome
* `left_on="col_esq"` / `right_on+"col_dir"`: quando os nomes são diferentes
* `how`define o tipo de `join` (`inner`, `left`, `right`, `outer`)

#### Tipos:

* `inner`: traz apenas os registros que existem nos DOIS DataFrames (interseção)
* `left`: traz todos os registros do DataFrame da ESQUERDA + correspondências da direita
* `right`: traz todos os registros do DataFrame da DIREITA + correspondências da esquerda
* `outer`: traz TODOS os registros dos dois DataFrames (união total)

In [174]:
import pandas as pd

# DataFrame principal (funcionários)
df = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "nome": ["Ana", "Bruno", "Carlos", "Diana"],
    "id_departamento": [10, 20, 30, None]
})

# DataFrame de departamentos
df_dep = pd.DataFrame({
    "id_departamento": [10, 20, 40],
    "nome_departamento": ["RH", "TI", "Financeiro"]
})

In [175]:
# Só traz quem tem correspondência nos dois
inner_join = pd.merge(df, df_dep, on="id_departamento", how="inner")
print(inner_join)

   id   nome  id_departamento nome_departamento
0   1    Ana             10.0                RH
1   2  Bruno             20.0                TI

In [176]:
# Traz todos do df e os correspondentes do df_dep (preenchendo com NaN onde não tem correspondência)
left_join = pd.merge(df, df_dep, on="id_departamento", how="left")
print(left_join)

   id    nome  id_departamento nome_departamento
0   1     Ana             10.0                RH
1   2   Bruno             20.0                TI
2   3  Carlos             30.0               NaN
3   4   Diana              NaN               NaN

In [177]:
# Traz todos do df_dep e os correspondentes do df (preenchendo com NaN onde não tem correspondência)
right_join = pd.merge(df, df_dep, on="id_departamento", how="right")
print(right_join)

    id   nome  id_departamento nome_departamento
0  1.0    Ana             10.0                RH
1  2.0  Bruno             20.0                TI
2  NaN    NaN             40.0        Financeiro

In [178]:
# Traz todos dos dois data frames, preenchendo com NaN onde não tem correspondência
outer_join = pd.merge(df, df_dep, on="id_departamento", how="outer")
print(outer_join)

    id    nome  id_departamento nome_departamento
0  1.0     Ana             10.0                RH
1  2.0   Bruno             20.0                TI
2  3.0  Carlos             30.0               NaN
3  NaN     NaN             40.0        Financeiro
4  4.0   Diana              NaN               NaN

---

Exercício 1. Faça uma função que receba um DataFrame e:

* Remova a primeira e a última linha
* Retorne um novo DataFrame com os dados restantes
* Não pode usar drop() diretamente com índice fixo (use lógica com iloc)

In [179]:
def remover_primeira_ultima_linha(df):
    # Verifica se o DataFrame tem pelo menos 3 linhas para evitar erros
    if len(df) < 3:
        raise ValueError("O DataFrame deve ter pelo menos 3 linhas para remover a primeira e a última.")
    
    # Usa iloc para selecionar todas as linhas, exceto a primeira (0) e a última (-1)
    novo_df = df.iloc[1:-1]
    
    return novo_df

# Exemplo de uso
df_exemplo = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50]
})
print("DataFrame original:")
print(df_exemplo)

df_modificado = remover_primeira_ultima_linha(df_exemplo)
print("DataFrame após remover a primeira e a última linha:")
print(df_modificado)

DataFrame original:
   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
DataFrame após remover a primeira e a última linha:
   A   B
1  2  20
2  3  30
3  4  40

Exercício 2. Crie um DataFrame com uma coluna chamada "valores" contendo números de 0 a 100.

* Calcule a soma de todos os valores pares
* Use filtragem booleana (não pode usar loop)

In [180]:
df_valores = pd.DataFrame({"valores": range(101)})
print(df_valores)
df_pares = df_valores[df_valores['valores'] % 2 == 0]
soma_pares = df_pares['valores'].sum()
print("Soma dos valores pares de 0 a 100:", soma_pares)

     valores
0          0
1          1
2          2
3          3
4          4
..       ...
96        96
97        97
98        98
99        99
100      100

[101 rows x 1 columns]
Soma dos valores pares de 0 a 100: 2550

Exercício 3. Crie um DataFrame com números de 0 a 100.

* Filtre apenas os números ímpares
* A partir desse resultado, filtre os números divisíveis por 3 e 5 ao mesmo tempo
* Crie uma nova coluna com a soma acumulada (cumsum)

In [181]:
df_valores = pd.DataFrame({"valores": range(101)})
print(df_valores)
df_pares = df_valores[df_valores['valores'] % 2 == 1]
df_divisiveis = df_pares[(df_pares['valores'] % 3 == 0) & (df_pares['valores'] % 5 == 0)].copy()
df_divisiveis['soma_acumulada'] = df_divisiveis['valores'].cumsum()
print(df_divisiveis)

     valores
0          0
1          1
2          2
3          3
4          4
..       ...
96        96
97        97
98        98
99        99
100      100

[101 rows x 1 columns]
    valores  soma_acumulada
15       15              15
45       45              60
75       75             135

Exercício 4. Faça uma função que receba um DataFrame com coluna "valores" e coluna "pesos"

* Retorne a média ponderada
* NÃO pode usar .mean() com peso nem função pronta
* Use apenas operações matemáticas

In [182]:
def media_ponderada(df):
    # Verifica se as colunas "valores" e "pesos" existem no DataFrame
    if 'valores' not in df.columns or 'pesos' not in df.columns:
        raise ValueError("O DataFrame deve conter as colunas 'valores' e 'pesos'.")
    
    # Calcula o produto dos valores pelos pesos
    produto = df['valores'] * df['pesos']
    
    # Soma dos produtos
    soma_produto = produto.sum()
    
    # Soma dos pesos
    soma_pesos = df['pesos'].sum()
    
    # Calcula a média ponderada
    media_ponderada = soma_produto / soma_pesos
    
    return media_ponderada

# Exemplo de uso
df_exemplo = pd.DataFrame({
    'valores': [10, 20, 30],
    'pesos': [1, 2, 3]
})
resultado = media_ponderada(df_exemplo)
print("Média ponderada:", resultado)

Média ponderada: 23.333333333333332

Exercício 5. Dado um DataFrame onde cada coluna representa uma prova:

```python
df = pd.DataFrame({
    "prova1": [10, 5, 8],
    "prova2": [7, 9, 6],
    "prova3": [8, 7, 9]
})
```

* Retorne qual prova teve a maior soma de notas

In [183]:
def prova_maior_soma(df):
    # Calcula a soma de cada coluna (prova)
    soma_provas = df.sum()
    
    # Encontra o nome da prova com a maior soma
    prova_maior = soma_provas.idxmax()
    
    return prova_maior

# Exemplo de uso
df_exemplo = pd.DataFrame({
    "prova1": [10, 5, 8],
    "prova2": [7, 9, 6],
    "prova3": [8, 7, 9]
})

prova_com_maior_soma = prova_maior_soma(df_exemplo)
print("A prova com a maior soma de notas é:", prova_com_maior_soma)

A prova com a maior soma de notas é: prova3

Exercício 6. Dado um DataFrame:

```python
df = pd.DataFrame({
    "aluno": ["Ana", "Bruno", "Carlos", "Diana"],
    "nota": [7.5, 4.0, 6.0, 3.5]
})
```

* Faça a média das notas
* Maior e menor nota + nome do aluno
* Liste alunos aprovados (nota ≥ 5)
* Liste alunos reprovados

In [184]:
def analise_notas(df):
    # Verifica se as colunas "aluno" e "nota" existem no DataFrame
    if 'aluno' not in df.columns or 'nota' not in df.columns:
        raise ValueError("O DataFrame deve conter as colunas 'aluno' e 'nota'.")
    
    # Calcula a média das notas
    media_notas = df['nota'].mean()
    
    # Encontra a maior nota e o nome do aluno correspondente
    maior_nota = df['nota'].max()
    aluno_maior_nota = df.loc[df['nota'] == maior_nota, 'aluno'].values[0]
    
    # Encontra a menor nota e o nome do aluno correspondente
    menor_nota = df['nota'].min()
    aluno_menor_nota = df.loc[df['nota'] == menor_nota, 'aluno'].values[0]
    
    # Lista de alunos aprovados (nota ≥ 5)
    alunos_aprovados = df[df['nota'] >= 5]['aluno'].tolist()
    
    # Lista de alunos reprovados (nota < 5)
    alunos_reprovados = df[df['nota'] < 5]['aluno'].tolist()
    
    return {
        "media_notas": media_notas,
        "maior_nota": (aluno_maior_nota, maior_nota),
        "menor_nota": (aluno_menor_nota, menor_nota),
        "alunos_aprovados": alunos_aprovados,
        "alunos_reprovados": alunos_reprovados
    }

# Exemplo de uso
df_exemplo = pd.DataFrame({
    "aluno": ["Ana", "Bruno", "Carlos", "Diana"],
    "nota": [7.5, 4.0, 6.0, 3.5]
})
resultados = analise_notas(df_exemplo)
print("Média das notas:", resultados["media_notas"])
print("Maior nota:", resultados["maior_nota"])
print("Menor nota:", resultados["menor_nota"])
print("Alunos aprovados:", resultados["alunos_aprovados"])
print("Alunos reprovados:", resultados["alunos_reprovados"])

Média das notas: 5.25
Maior nota: ('Ana', 7.5)
Menor nota: ('Diana', 3.5)
Alunos aprovados: ['Ana', 'Carlos']
Alunos reprovados: ['Bruno', 'Diana']

Exercício 7. Dado:

```python
df = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Diana", "Eduardo"],
    "idade": [23, 35, 29, 41, 22],
    "salario": [2500, 4000, 3200, 5000, 1800]
})
```

* Retorne: apenas as colunas "nome" e "salario" das pessoas com salário > 3000 e idade < 40
* Cre uma coluna "categoria": "Baixo" → salário < 3000; "Médio" → 3000 a 4000; "Alto" → > 4000. Use apply() ou np.where()

In [185]:
def classificar_categoria(salario):
    if salario < 3000:
        return "Baixo"
    elif 3000 <= salario <= 4000:
        return "Médio"
    else:
        return "Alto"

df = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Diana", "Eduardo"],
    "idade": [23, 35, 29, 41, 22],
    "salario": [2500, 4000, 3200, 5000, 1800]
})
df['categoria'] = df['salario'].apply(classificar_categoria)
print(df)

      nome  idade  salario categoria
0      Ana     23     2500     Baixo
1    Bruno     35     4000     Médio
2   Carlos     29     3200     Médio
3    Diana     41     5000      Alto
4  Eduardo     22     1800     Baixo

Exercício 8. Dado um DataFrame com salários:

* Ordene do maior para o menor salário
* Crie uma coluna "ranking" com a posição de cada funcionário

In [186]:
def ordenar_ranking(df):
    # Ordena o DataFrame por salário (do maior para o menor)
    df_ordenado = df.sort_values("salario", ascending=False).copy()
    
    # Cria a coluna "ranking" com a posição de cada funcionário
    df_ordenado['ranking'] = range(1, len(df_ordenado) + 1)
    
    return df_ordenado

df = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Diana", "Eduardo"],
    "salario": [2500, 4000, 3200, 5000, 1800]
})
df_ranking = ordenar_ranking(df)
print(df_ranking)

      nome  salario  ranking
3    Diana     5000        1
1    Bruno     4000        2
2   Carlos     3200        3
0      Ana     2500        4
4  Eduardo     1800        5

Exercício 9. Dado:

```python
df = pd.DataFrame({
    "departamento": ["TI", "TI", "RH", "RH", "Financeiro"],
    "salario": [5000, 7000, 4000, 4500, 8000]
})
```

* Faça a média salarial por departamento
* Soma salarial por departamento
* Quantidade de funcionários

In [187]:
df = pd.DataFrame({
    "departamento": ["TI", "TI", "RH", "RH", "Financeiro"],
    "salario": [5000, 7000, 4000, 4500, 8000]
})

media_salarial = df.groupby("departamento")["salario"].mean()
soma_salarial = df.groupby("departamento")["salario"].sum()
quantidade_funcionarios = df.groupby("departamento").size()

print("Média salarial por departamento:")
print(media_salarial)
print("\nSoma salarial por departamento:")
print(soma_salarial)
print("\nQuantidade de funcionários por departamento:")
print(quantidade_funcionarios)

Média salarial por departamento:
departamento
Financeiro    8000.0
RH            4250.0
TI            6000.0
Name: salario, dtype: float64

Soma salarial por departamento:
departamento
Financeiro     8000
RH             8500
TI            12000
Name: salario, dtype: int64

Quantidade de funcionários por departamento:
departamento
Financeiro    1
RH            2
TI            2
dtype: int64